services:
  api:
    build:
      context: ./docker/go
      target: production
    environment:
      - PORT=${API_PORT:-3100}
      - SIGNING_KEY=${SIGNING_KEY:-AllYourBase}
    tty: true
    ports:
      - ${API_PORT}:${API_PORT}
