name: Api test

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup go1.21.6
        uses: actions/setup-go@v5
        with:
          go-version: 1.21.6

      - name: Run api test
        run: make test